### ISSUE TITLE
Protobuf location

### ISSUE THREAD

**Issue by ilovemihoyo** [nitrog0d/ProtoDumper#2]
Hey, is this repo still working? 

I can't find any trace of protobuf in Assembly-CSharp.dll from UserAssembly.dll

**Comment by nitrog0d** [comment]
On the README it says you need deobfuscated assemblies, all the names are obfuscated.

**Comment by ilovemihoyo** [comment]
Thanks for the response,

Can you give me some hints on how to deobfuscated class names? I have been searching but cant seem to find anything useful or easy to understand.
